spring:
  application:
    name: customer

server:
  port: 1111

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: false
